export const CHANGE_VIEWTOON = "CHANGE_VIEWTOON";
export const CHANGE_VIEWBANNERIMAGE = "CHANGE_VIEWBANNERIMAGE";
export const CHANGE_SORTTYPE = "CHANGE_SORTTYPE";
export const LOAD_TOONLIST = "LOAD_TOONLIST";
