export const CHANGE_LISTTYPE = "CHANGE_LISTTYPE";
export const CHANGE_WEEKDAY = "CHANGE_WEEKDAY";
// export const INIT_CONTENTS_SWIPER = "INIT_CONTENTS_SWIPER";
// export const RECEIVE_WEEKALLTOON = "RECEIVE_WEEKALLTOON";
