export const CHANGE_VIEWTOON = "CHANGE_VIEWTOON";
export const CHANGE_VIEWBANNERIMAGE = "CHANGE_VIEWBANNERIMAGE";
export const CHANGE_SORTTYPE = "CHANGE_SORTTYPE";
export const LOAD_TOONLIST = "LOAD_TOONLIST";

export const LOAD_VIEWTOON = "LOAD_VIEWTOON";
export const ADD_VIEWTOON = "ADD_VIEWTOON";
export const UPDATE_VIEWTOON = "UPDATE_VIEWTOON";
export const DELETE_VIEWTOON = "DELETE_VIEWTOON";
